version: '3.8'

services:
  api-service:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    image: api-service-app
    container_name: api-service-app
    environment:
      DATA_SERVICE_BASE_URL: ${DATA_SERVICE_BASE_URL}
      DATA_SERVICE_PORT: ${DATA_SERVICE_PORT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_APPOINTMENTS_TOPIC: ${KAFKA_APPOINTMENTS_TOPIC}
      KAFKA_DOCTORS_TOPIC: ${KAFKA_DOCTORS_TOPIC}
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - data-service
    networks:
      - medical-net

  data-service:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    image: data-service-app
    container_name: data-service-app
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      DATA_SERVICE_PORT: ${DATA_SERVICE_PORT}
      KAFKA_APPOINTMENTS_TOPIC: ${KAFKA_APPOINTMENTS_TOPIC}
      KAFKA_DOCTORS_TOPIC: ${KAFKA_DOCTORS_TOPIC}
      DB_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    expose:
      - "${DATA_SERVICE_PORT}"
    depends_on:
      - postgres
      - kafka
    networks:
      - medical-net

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - medical-net

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - 9092
    depends_on:
      - zookeeper
    networks:
      - medical-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    networks:
      - medical-net

networks:
  medical-net:
    driver: bridge

volumes:
  postgres-data:
